- name: Configure Framework laptop
  hosts: localhost
  become_method: doas

  tasks:

    - name: Create cwmrc 
      copy:
        dest: ~/.cwmrc
        content: |
          borderwidth 1
          sticky yes
            
          bind-key M-1 group-only-1
          bind-key M-2 group-only-2
          bind-key M-3 group-only-3
          bind-key M-4 group-only-4
          bind-key M-5 group-only-5
          bind-key M-6 group-only-6

          bind-key MS-1 window-movetogroup-1
          bind-key MS-2 window-movetogroup-2
          bind-key MS-3 window-movetogroup-3
          bind-key MS-4 window-movetogroup-4
          bind-key MS-5 window-movetogroup-5
          bind-key MS-6 window-movetogroup-6

          color activeborder rgb:cf/b5/3b
          color inactiveborder rgb:cf/b5/3b
          color menubg rgb:00/00/00
          color menufg rgb:cf/cf/cf
          color font rgb:cf/cf/cf
          color selfont rgb:00/00/00

          gap 28 00 00 00

          bind-key CM-Return "/usr/local/bin/terminator -p 'Monokai Soda'"
          bind-key CM-b "/usr/local/bin/firefox -private https://start.duckduckgo.com"
          bind-key CM-z "/usr/local/bin/scrot '%m-%d_screenshot.png' -e 'mv $f ~/pics'"
          bind-key CM-8 "/usr/bin/setxkbmap ru phonetic"
          bind-key CM-9 "/usr/bin/setxkbmap us"
          bind-key CM-h window-htile
          bind-key CM-v window-vtile


    - name: Set ~/.xsession
      copy:
        dest: ~/.xsession
        content: |
          xinput set-prop "/dev/wsmouse" "Device Accel Constant Deceleration" 0.5
          export GDK_SCALE=2.0
          export QT_SCALE_FACTOR=1.0
          feh --bg-fill ~/pics/bg
          cwm

    - name: Set tap to click
      copy:
        dest: /etc/wsconsctl.conf
        content: |
          mouse.tp.tapping=1,3,2
      become: yes

    - name: Enable tap to click
      command: wsconsctl mouse.tp.tapping=1,3,2
      become: yes

    - name: Install packages
      openbsd_pkg:
        name:
          - colorls--
          - feh--
          - fira-fonts--
          - firefox--
          - git--
          - keepassxc--
          - libsodium--
          - lynx--
          - mtr--
          - nmap--
          - obsdfreqd--
          - openconnect--
          - py3-pip--
          - quirks--
          - terminator--
          - vim--no_x11
        state: installed
      become: yes

    - name: Setup terminator
      copy:
        dest: ~/.config/terminator/config
        content: |
          [global_config]
            dbus = False
            handle_size = 1
            enabled_plugins = LaunchpadBugURLHandler, LaunchpadCodeURLHandler, APTURLHandler, TerminatorThemes
          [keybindings]
            split_horiz = <Alt>minus
            split_vert = <Alt>backslash
          [profiles]
             [[default]]
                cursor_color = "#aaaaaa"
                font = Fira Mono 14
                show_titlebar = False
                scrollbar_position = hidden
                scrollback_infinite = True
                use_system_font = False
             [[Monokai Soda]]
                 background_color = "#1a1a1a"
                 cursor_color = "#f6f7ec"
                 font = Fira Mono 14
                 foreground_color = "#c4c5b5"
                 show_titlebar = False
                 scrollbar_position = hidden
                 scrollback_infinite = True
                 palette = "#1a1a1a:#f4005f:#98e024:#fa8419:#9d65ff:#f4005f:#58d1eb:#c4c5b5:#625e4c:#f4005f:#98e024:#e0d561:#9d65ff:#f4005f:#58d1eb:#f6f6ef"
                 login_shell = True
                 use_system_font = False
            [layouts]
               [[default]]
                  [[[window0]]]
                      type = Window
                      parent = ""
                  [[[child1]]]
                      type = Terminal
                      parent = window0
            [plugins]

    - name: Enable and start apmd service
      service:
        name: apmd
        enabled: yes
        state: started
      become: yes

    - name: Enable and start xenodm
      service:
        name: xenodm
        enabled: yes
        state: started
      become: yes
